name: Build and Release App

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  APP_NAME: "Cool-App"
  FLUTTER_VERSION: "3.24.0"
  ZSIGN_VERSION: "0.7"

jobs:
  build-and-release-ios-ipa:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      # Checkout branch
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          path: .

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install the CLI tool
        run: cargo install 'flutter_rust_bridge_codegen'

      - name: flutter pub get
        run: flutter pub get

      - name: setup signing environment
        env:
          P12_BASE64: ${{ secrets.P12_CERTIFICATE }}
          PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE }}
        run: |
          echo "$P12_BASE64" | base64 -d > certificate.p12
          echo "$PROVISIONING_PROFILE_BASE64" | base64 -d > profile.mobileprovision
          curl -L -o zsign.zip "https://github.com/zhlynn/zsign/releases/download/v${{ env.ZSIGN_VERSION }}/zsign-v${{ env.ZSIGN_VERSION }}-macos-x64.zip"
          unzip zsign.zip
          chmod +x zsign || chmod +x zsign-*

      - name: build ios
        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: |
          flutter build ios --release --no-codesign
          mkdir -p build/ios/iphoneos/Payload
          ln -s ../Runner.app build/ios/iphoneos/Payload/Runner.app
          ./zsign -f -k ./certificate.p12 -p "$P12_PASSWORD" -m ./profile.mobileprovision ./build/ios/iphoneos/Payload/Runner.app
          cd build/ios/iphoneos
          zip -r ./Cool-App-${{ github.ref_name }}-ios.ipa Payload

      - name: upload artifact ios ipa
        uses: actions/upload-artifact@v4
        with:
          name: Cool-App-${{ github.ref_name }}-ios
          path: "build/ios/iphoneos/Cool-App-*.ipa"

      - name: release package ios ipa
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/ios/iphoneos/Cool-App-*.ipa"
          allowUpdates: true

  call-workflow-sideloading:
    needs: build-and-release-ios-ipa
    uses: ./.github/workflows/update_source.yml
    with:
      RELEASE_TAG: ${{ github.ref_name }}